base_url = "https://www.neverlight.com/"
generate_rss = true
compile_sass = true

title = "Neverlight"
description = "Chaos, Discord, Disharmony"

theme = "zola-clean-blog"
taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Mental"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
#clean_blog_social = [
#    {url = "https://twitter.com", icon="fab fa-twitter"},
#    {url = "$BASE_URL/rss.xml", icon="fas fa-rss"}
#]
[markdown]
highlight_code = true
