base_url = "https://www.neverlight.com/"
generate_rss = true
compile_sass = true

title = "Neverlight"
description = "Chaos, Discord, Disharmony"

theme = "neverlight-theme"
taxonomies = [
    {name = "categories", rss = true, paginate_by=5},
    {name = "tags", rss = true, paginate_by=5},
]

[extra]
author = "Mental"
clean_blog_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/contact", name = "Contact"}
]
[markdown]
highlight_code = true
